#!/usr/bin/env bash

echo 'Fetching forecast data'
count=0

for p in $(seq 0 100 100000); do
	echo "Page offset ${p}"
	curl --silent --show-error --fail 'https://www.metaculus.com/api2/categories/?limit=100&offset='$p >> metaculus_categories.json
	if grep -Eo '"next":null' <metaculus_categories.json; then break; fi
	echo >> metaculus_categories.json
	count=$((count + 1))
	sleep 10
done

echo "Got $count pages"
