#!/usr/bin/env bash
jq <$1 '{"question_id": .id, "open_time": .publish_time, "close_time": .close_time, "resolve_time": .resolve_time, "outcome": .resolution, "question_title": .title, "short_title": .title_short, "categories": .categories, "q_desc": .description, "resolution_criteria": .resolution_criteria}' |
./full_json
